export enum FailureCode {
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  REFERENCE_NOT_FOUND = 'REFERENCE_NOT_FOUND',
  DUPLICATE_TRANSACTION = 'DUPLICATE_TRANSACTION',
  TRANSACTION_ALREADY_SETTLED = 'TRANSACTION_ALREADY_SETTLED',
  OPTIMISTIC_LOCK_ERROR = 'OPTIMISTIC_LOCK_ERROR',
  INVALID_OPERATION = 'INVALID_OPERATION',
  IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',
  INVALID_CURRENCY = 'INVALID_CURRENCY',
  INVALID_AMOUNT = 'INVALID_AMOUNT',
}